### ISSUE TITLE
Issue with cineon inversion

### ISSUE THREAD

**Issue by 33ILMX** [mikaelsundell/dctl#3]
Hi Mikael, firstly thank you for putting together these applications!

I am however having some issues getting a correct output from negative to positive Cineon.
I've tried both with a Linear TIFF and with a RAWtoACES EXR file.
Both of them come out very dim (the EXR worse).

Would you have any ideas what might be going on? 
(probably I'm not doing something correctly)

EXR:
<img width="1335" alt="Screenshot 2024-09-21 at 6 16 20 PM" src="https://github.com/user-attachments/assets/dd66e276-73b9-4555-b464-c48866529738">

Linear TIFF:
<img width="621" alt="Screenshot 2024-09-21 at 6 17 21 PM" src="https://github.com/user-attachments/assets/bb8d9f10-f57b-4bcd-b9a9-2dc8e4000efe">

**Comment by mikaelsundell** [comment]
Thanks for the report, any chance you can post the original TIFF and I will check it out 👍🏻

**Comment by 33ILMX** [comment]
Thanks for taking a look, I've linked both the RAW and Lin TIFF below.
https://we.tl/t-ZzQu5k08Pq

**Comment by mikaelsundell** [comment]
Give me a few hours

**Comment by mikaelsundell** [comment]
Perth, here we go!

Sample your density dmin, typically film base, in Nuke or similar software.
Set the density base values for the inversion in Resolve
Adjust scaling for black and whitepoint depending on your scan etc

![Sample base](https://github.com/user-attachments/assets/d7269f33-d6b1-4f74-af38-37fec15390cf)

<img width="385" alt="MS-Cineon-Invert" src="https://github.com/user-attachments/assets/30b233e2-58f1-44b8-8554-df97377c5941">

<img width="1357" alt="TIFF Invert" src="https://github.com/user-attachments/assets/ff0c66fc-0f06-4707-9279-db9b29d6d211">


Quick test with resize + Kodak 2383 (MS-LogC3-Print dctl) + shadow lift.

<img width="1207" alt="Kodak 2383 D55" src="https://github.com/user-attachments/assets/2d547f41-5228-4d05-9713-4b34ec4627db">

**Comment by 33ILMX** [comment]
Thanks Mikael! 
I wrote a py script to auto find the film base and sample its RGB values, but I just want to clarify I would need to sample the base in 32bit float values, right? (up to 8 decimals)

Then those values plug into the Dmin Density.

But the Density scale you are doing by eye, is that correct?

**Comment by mikaelsundell** [comment]
I'm using OpenImageIO with python in a similar way, should work. The precision is probably not as important (16/32-bit), you can give it a try and AB test. 

The color temperature/ camera/ scanner/ calibration etc will all influence the colors so I would start by making it simple and eye ball per roll/ photo capture setup to begin with. Some people do advanced color calibration pre-processing. Not sure with negatives how much it contributes to consistency. Raw to aces with camera meta data is what I use and it works as a DIY solution with reproducible results.

**Comment by 33ILMX** [comment]
Im curious how you approached your process, as far as I can tell it seems to differ from the usual cineon inversion.
Which would be (without using R/G/B LED adjustment), white balancing (e.g. per channel linear gain to balance the white point) which upon inversion should get you to 95/1023, then inverting.
(95 + log10(1/T)(1023/DensityRange))/1023)
Typically since it's not practical to map the values of every stock/dev/etc you just set 95 black point then let the rest of the values fall where they do. This should avoid needing to do any major density scaling.

Would love to hear your thoughts on inversion.

**Comment by mikaelsundell** [comment]
This is the formula:

```
__DEVICE__ float3 invert_cineon(float3 rgb, float3 scale, float3 dmin) {
    float3 invert = make_float3(offset, offset, offset);
    invert += scale * log10f3(dmin / rgb) / steps();
    invert /= bitdepth;
    return invert;
}
```

**log10f3(dmin / rgb):**
This applies the inversion because film density is logarithmic in terms of light transmission.

Quick example using linear density from the dmin base of linear 2.56 for the R channel (typical values):

A black patch, representing high transmission in the negative, has a linear value of 1.91 and a ratio of 1.34.
A white patch, representing low transmission through the negative, has a linear value of 0.7 and a ratio of 3.65.
These values fall into place after the offset is applied, such as 95 when we use the log10f3 function.

**scale:**
The scale parameter adjusts the gain of the inversion, allowing fine-tuning based on the characteristics of the film stock or the desired look. You can also use gain before the inversion to increase (lower) or decrease (higher) the gamma of the negative. Say the film was under developed, density can vary with processing chemicals etc.

**steps():**
This is a normalization factor, representing the number of "steps" in the quantization process.

This process can be done in many ways. Personally, I use a Cineon chart (see the README for Cineon 10-bit DPX and the logctool) with known values for each photographic stop to ensure my process is accurate. I never change the camera capture settings or the lightbox, and I maintain consistent temperature and development time. This allows me to reuse the same node values for dmin and other parameters across different film stocks.

Once we're in the Cineon log space, we can use Resolve's built-in tools to convert to other color spaces. Negatives are a bit unpredictable and can behave differently from time to time, which is part of their charm. I try not to be too scientific about it and go with the variation.

Scaling and additional curve adjustments are typically necessary on my end because my garage development process isn't always as precise as in a professional environment :-) Factors such as the age of the chemicals, shifts in gamma, and deviations in density curves often require fine-tuning.

Send me a PM if you need more examples.
